# Generated by Django 5.2 on 2025-04-26 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BlogPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("category", models.CharField(max_length=100)),
                ("content", models.TextField()),
                ("author", models.CharField(max_length=100)),
                ("publish_date", models.DateField()),
                ("read_time", models.CharField(max_length=10)),
                (
                    "author_image",
                    models.ImageField(blank=True, null=True, upload_to="authors/"),
                ),
                (
                    "background_image",
                    models.ImageField(blank=True, null=True, upload_to="backgrounds/"),
                ),
            ],
        ),
    ]
